name: qce-tut-jup
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.1.2=py39h06a4308_0
  - python=3.9.13=haa1d7c7_1
  - readline=8.1.2=h7f8727e_1
  - setuptools=63.4.1=py39h06a4308_0
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022c=h04d1e81_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h5eee18b_3
  - pip:
    - anyio==3.6.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.8
    - attrs==22.1.0
    - babel==2.10.3
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - contourpy==1.0.5
    - cycler==0.11.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - executing==1.0.0
    - fastjsonschema==2.16.1
    - fonttools==4.37.2
    - idna==3.4
    - importlib-metadata==4.12.0
    - ipykernel==6.15.3
    - ipython==8.5.0
    - ipython-genutils==0.2.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - json5==0.9.10
    - jsonschema==4.16.0
    - jupyter-client==7.3.5
    - jupyter-core==4.11.1
    - jupyter-server==1.18.1
    - jupyterlab==3.4.7
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.15.1
    - jupyterquiz==2.0.6
    - jupytext==1.14.1
    - kiwisolver==1.4.4
    - liepy==0.1.3
    - lxml==4.9.1
    - markdown-it-py==2.1.0
    - markupsafe==2.1.1
    - matplotlib==3.6.0
    - matplotlib-inline==0.1.6
    - mdit-py-plugins==0.3.0
    - mdurl==0.1.2
    - mistune==2.0.4
    - nbclassic==0.4.3
    - nbclient==0.6.8
    - nbconvert==7.0.0
    - nbformat==5.5.0
    - nest-asyncio==1.5.5
    - notebook==6.4.12
    - notebook-shim==0.1.0
    - numpy==1.23.3
    - packaging==21.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.31
    - psutil==5.9.2
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.2.1
    - pyyaml==6.0
    - pyzmq==24.0.0
    - qutip==4.7.0
    - requests==2.28.1
    - scipy==1.9.1
    - send2trash==1.8.0
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.5.0
    - terminado==0.15.0
    - tinycss2==1.1.1
    - toml==0.10.2
    - tomli==2.0.1
    - tornado==6.2
    - traitlets==5.4.0
    - urllib3==1.26.12
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - zipp==3.8.1
